services:
  - type: web
    name: portfolio
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
