services:
  - type: web
    name: portfolio
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python portfolio/manage.py collectstatic --noinput && python portfolio/manage.py migrate"
    startCommand: "gunicorn --chdir portfolio portfolio.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
